[workspace]
authors = ["harvey <harveytseng2@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "finance-moe-kernel"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.5.0.dev2025062805,<26"
