[workspace]
authors = ["harvey <harveytseng2@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "finance-moe-kernel"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.5.0.dev2025062815,<26"
pytorch = ">=2.7.1,<3"
torchvision = ">=0.22.0,<0.23"
matplotlib = ">=3.10.3,<4"
pandas = ">=2.3.0,<3"
numpy = ">=2.3.0,<3"
jupyter = ">=1.1.1,<2"
scikit-learn = ">=1.7.0,<2"
yfinance = ">=0.2.64, <0.3"
